CREATE TABLE sample(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	list VARCHAR(200) NOT NULL,
	date date NOT NULL,
	PRIMARY KEY(id)
);
CREATE TABLE form(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	comment VARCHAR(100) NOT NULL,
	yakusyoku VARCHAR(100) NOT NULL,
	busyo VARCHAR(100) NOT NULL,
	syumi VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);     